#!/bin/bash
python behavioral_cloning/save_opt_trajectories_jpeg.py --n_trajectories=20000 --env=HabitatImageNav-apartment_0
python behavioral_cloning/save_opt_trajectories_jpeg.py --n_trajectories=20000 --env=HabitatImageNav-apartment_1
python behavioral_cloning/save_opt_trajectories_jpeg.py --n_trajectories=20000 --env=HabitatImageNav-apartment_2
python behavioral_cloning/save_opt_trajectories_jpeg.py --n_trajectories=20000 --env=HabitatImageNav-frl_apartment_0
python behavioral_cloning/save_opt_trajectories_jpeg.py --n_trajectories=20000 --env=HabitatImageNav-frl_apartment_1
python behavioral_cloning/save_opt_trajectories_jpeg.py --n_trajectories=20000 --env=HabitatImageNav-frl_apartment_2
python behavioral_cloning/save_opt_trajectories_jpeg.py --n_trajectories=20000 --env=HabitatImageNav-frl_apartment_3
python behavioral_cloning/save_opt_trajectories_jpeg.py --n_trajectories=20000 --env=HabitatImageNav-frl_apartment_4
python behavioral_cloning/save_opt_trajectories_jpeg.py --n_trajectories=20000 --env=HabitatImageNav-frl_apartment_5
python behavioral_cloning/save_opt_trajectories_jpeg.py --n_trajectories=20000 --env=HabitatImageNav-room_0
python behavioral_cloning/save_opt_trajectories_jpeg.py --n_trajectories=20000 --env=HabitatImageNav-room_1
python behavioral_cloning/save_opt_trajectories_jpeg.py --n_trajectories=20000 --env=HabitatImageNav-room_2
python behavioral_cloning/save_opt_trajectories_jpeg.py --n_trajectories=20000 --env=HabitatImageNav-hotel_0
python behavioral_cloning/save_opt_trajectories_jpeg.py --n_trajectories=20000 --env=HabitatImageNav-office_0
python behavioral_cloning/save_opt_trajectories_jpeg.py --n_trajectories=20000 --env=HabitatImageNav-office_1
python behavioral_cloning/save_opt_trajectories_jpeg.py --n_trajectories=20000 --env=HabitatImageNav-office_2
python behavioral_cloning/save_opt_trajectories_jpeg.py --n_trajectories=20000 --env=HabitatImageNav-office_3
python behavioral_cloning/save_opt_trajectories_jpeg.py --n_trajectories=20000 --env=HabitatImageNav-office_4
